### ISSUE TITLE
Dependency Parser Issue

### ISSUE THREAD

**Issue by KadirYigitUS** [vngrs-ai/vnlp#15]
Tried on Colab
!pip install vngrs-nlp
from vnlp import DependencyParser
dependency_parser = DependencyParser()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-7-7ad7c31e95fb>](https://localhost:8080/#) in <cell line: 1>()
----> 1 dependency_parser = DependencyParser()
      2 # dependency_parser = DependencyParser(model = 'SPUContextDP', evaluate = True)

4 frames
[/usr/local/lib/python3.10/dist-packages/keras/src/backend/common/variables.py](https://localhost:8080/#) in standardize_shape(shape)
    528             raise ValueError("Undefined shapes are not supported.")
    529         if not hasattr(shape, "__iter__"):
--> 530             raise ValueError(f"Cannot convert '{shape}' to a shape.")
    531         if config.backend() == "tensorflow":
    532             if isinstance(shape, tf.TensorShape):

ValueError: Cannot convert '8' to a shape.

**Comment by meliksahturker** [comment]
Thanks for the report.
This is resolved with 0.2.4. Please update.
